#!/bin/bash

self_update() {
  SELF_UPDATE="$1"
  if [ "$SELF_UPDATE" == false ]; then return; fi

  REPO_URL="https://raw.githubusercontent.com/cstaud/pre-commit-hook/master"
  SELF="$0"
  REMOTE_SCRIPT="$REPO_URL/$SELF"

  echo "Checking for self-update ..."
  diff=$(diff "$SELF" <(curl -s "$REMOTE_SCRIPT"))

  if [ -z "$diff" ]
  then
    echo "Already running on latest version, yeah!"
  else
    echo "Downloading latest version..."

    if ! curl --output "$SELF" "$REMOTE_SCRIPT"; then
      echo "Failed: Error while trying to curl new version!"
      echo "File requested: REMOTE_SCRIPT"
      exit 1
    fi
    echo "Done. Quitting deprecated version now."
    exit 0
  fi
}

go_fmt() {
  go_fmt_diff=$(docker run --rm -v "$ROOT_DIR":/app -w /app golang:1.14 gofmt -l .)
  if [ -z "$go_fmt_diff" ]; then
    echo "Your go code looks nice."
  else
    echo "Dude!? Format your go code:"
    echo "$go_fmt_diff"
    exit 1
  fi
}

java_format() {
  java_format_diff=$(docker run --rm -v "$ROOT_DIR":/src openjdk:alpine sh -c "wget --quiet https://github.com/google/google-java-format/releases/download/google-java-format-1.6/google-java-format-1.6-all-deps.jar && find /src -name '*.java' | xargs java -jar google-java-format-1.6-all-deps.jar -n")
  if [ -z "$java_format_diff" ]; then
    echo "Your java code looks ... ok, its still java ;-)"
  else
    echo "Dude!? Your java code hurt my eyes!"
    echo "$java_format_diff"
    exit 1
  fi
}

main() {
  echo "Startet pre-commit hook"
  go_fmt
  java_format
}

ROOT_DIR="$(git rev-parse --show-toplevel)"
[[ -d "${ROOT_DIR}" ]] || exit 1


self_update true
main